name: tap_game
description: A simple tap game.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.0
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/tap.wav
    - assets/sounds/game_over.wav
